apiVersion: v1
kind: Config
clusters:
- name: "kuba-cluster"
  cluster:
    server: "https://rancher.cloud.e-infra.cz/k8s/clusters/c-m-qvndqhf6"

users:
- name: "kuba-cluster"
  user:
    token: "kubeconfig-u-ewt6hxi5z577v98:9wj5s8z56xkhsqbb28fzdw9lxtv7xtlnm8p5dhq9zl2dxgv7lnmpgn"


contexts:
- name: "kuba-cluster"
  context:
    user: "kuba-cluster"
    cluster: "kuba-cluster"

current-context: "kuba-cluster"
